<div class="social col-md-6">
				<ul class="list-unstyled list-group  ">
					<li class="col-md-12  text-center colr1"><a href="#" target="_blank">
						<h1><p><span class="icon-facebook"></span></p></h1>
					</a></li>
					
					
					<li class="col-md-12 text-center colr2"><a href="#" target="_blank">
						<h1><p><span class="icon-twitter"></span></p></h1>
					</a></li>
					
					
					<li class="col-md-12 text-center colr3"><a href="#" target="_blank">
						<h1><p><span class="icon-instagram"></span></p></h1>
					</a></li>
					
				</ul>
			</div>