<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header clhm">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Registro:</h4>
      </div>
      <div class="modal-body">
        <form action="php/reg.php" enctype="multipart/form-data" class="form-horizontal" method="POST">
          <div class="form-group">
            <label for="inputEmail3" class="col-sm-2 control-label " required="required">Nombre</label>
            <div class="col-sm-10">
              <input type="text" class="form-control" autocomplete="off"placeholder="nombre" name="nombre">
            </div>
          </div>
          <div class="form-group">
            <label for="inputEmail3" class="col-sm-2 control-label"required="required">Apellido</label>
            <div class="col-sm-10">
              <input type="text" class="form-control" autocomplete="off"placeholder="Apellido" name="apellido">
            </div>
          </div>
          <div class="form-group">
            <label for="inputEmail3" class="col-sm-2 control-label"required="required">Telefono</label>
            <div class="col-sm-10">
              <input type="tel"pattern="[0-9]{9}"class="form-control" autocomplete="off"placeholder="Telefono"name="telefono">
            </div>
          </div>
          <div class="form-group">
            <label for="inputEmail3" class="col-sm-2 control-label"required="required">Email</label>
            <div class="col-sm-10">
              <input type="email" class="form-control" id="inputEmail3" autocomplete="off"placeholder="Email"name="email">
            </div>
          </div>
          <div class="form-group">
            <label for="inputPassword3" class="col-sm-2 control-label"required="required">Contraseña</label>
            <div class="col-sm-10">
              <input type="password" class="form-control" id="inputPassword3" autocomplete="off"placeholder="Contraseña"name="contrasena">
            </div>
          </div>
          <div class="form-group">
            <label for="inputPassword3" class="col-sm-2 control-label"required="required">Repetir contraseña</label>
            <div class="col-sm-10">
              <input type="password" class="form-control" id="inputPassword3" autocomplete="off"placeholder="Contraseña"name="rcontrasena">
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
              <div class="checkbox">
                <label>
                  <input type="checkbox"checked> permitir que se le envie publicidad al correo
                </label>
              </div>
            </div>
          </div>
     
      </div>
      <div class="modal-footer">
        <button type="reset" class="btn btn-default" data-dismiss="modal" >Cerrar</button>
        <button type="submit" class="btn btn-primary"data-loading-text="Loading..." id="myButton">Registrar</button>
      </div>
     </form>
    </div>
  </div>
</div>

