<?php
$plantilla=new plantilla();
	class plantilla{
	function __construct(){
?>
<!DOCTYPE html>
<html lang="es">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
		<!-- Bootstrap -->
		<link href="<?php  echo control::ruta();?>public/css/bootstrap.css" rel="stylesheet type="text/css"">
		<link href="<?php  echo control::ruta();?>public/EstilosP.css" rel="stylesheet type="text/css"">
		<link rel="stylesheet" href="<?php  echo control::ruta();?>public/css/carousel.css">
		<link rel="stylesheet" href="<?php  echo control::ruta();?>public/fonts/style.css">
		<title>..::Carcajadas XD::..</title>
	</head>
	<body>
		
		
		
		<!--- >header<-->
		
		
		<?php
			include "nabar.phtml";
	
		?>
		
		<!-- /menu -->
		<div class="menus col-md-3 ">
			<ul class="list-group  list-unstyled">
				<li class=" col-md-12 rl mf text-center mn1">
					<a href="./"><img class="img-responsive icn" width="65"src="public/img/iconM/1423349013_Star_full.png" alt="INICIO"></a>
					<p class="lead txtm"><a href="<?php echo control::ruta()?>?accion=index">INICIO</a></p>
				</li>
				<li class=" col-md-12 rl mf text-center mn2">
					<a href="#"><img class="img-responsive icn" width="65"src="public/img/iconM/1423348825_Cart.png" alt="PRODUCTOS"></a>
					<p class="lead txtm"><a href="#">PRODUCTOS</a></p>
				</li>
				<li class=" col-md-12 rl mf text-center mn3">
					<a href="#"><img class="img-responsive icn" width="65"src="public/img/iconM/1423348812_Discount.png" alt="PROMOCIONES"></a>
					<p class="lead txtm"><a href="#">PROMOCIONES</a></p>
				</li>
				<li class=" col-md-12 rl mf text-center mn4">
					<a href="<?php echo control::ruta()?>?accion=preguntas"><img class="img-responsive icn" width="65"src="public/img/iconM/1423349025_Help.png" alt="PREGUNTAS"></a>
					<p class="lead txtm"><a href="#">PREGUNTAS</a></p>
				</li>
				<li class=" col-md-12 rl mf text-center mn5">
					<a href="#"><img class="img-responsive icn" width="65"src="public/img/iconM/1423357261_Phone.png" alt="CONTACTO"></a>
					<p class="lead txtm"><a href="#">CONTACTO</a></p>
				</li>
			</ul>
			<?php 
				include "inmenu.phtml";
			?>
		</div>
		
		<div class="col-md-9  well">
			<?php
				}
				function __destruct(){
			?>
		</div>
		<footer class=" container-fluid footer col-md-12">
			
			<p>footer XD</p>
			
		</footer>
		
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
		<script src="<?php  echo control::ruta();?>public/js/bootstrap.js"></script>
		<script src="<?php  echo control::ruta();?>public/js/holder.js"></script>
		<script src="<?php  echo control::ruta();?>public/js/functions.js"></script>
	</body>
</html>
<?php
	}
}