<div class="row">
	<div class="col-sm-5 col-md-3 ">
		<div class="thumbnail  ">
			<a href="#"><img class="imt img-responsive" src="http://www.buscatrabajo.org/wp-content/Los-principales-requisitos-para-encontrar-empleo-en-la-actualidad.jpg" alt="..."></a>
			<div class="caption tmt">
				<h3>Donde puede encontrarnos</h3>
				
				<p><a href="#" class="btn btn-primary " role="button">Button <span class="icon-globe"></span></a> </p>
			</div>
		</div>
	</div>
	<div class="col-sm-5 col-md-3 ">
		<div class="thumbnail  ">
			<a href="#"><img class="imt img-responsive" src="http://www.centroantaris.org/wp-content/uploads/2014/09/quienes-somos2.jpg" alt="..."></a>
			<div class="caption tmt">
				<h3>Quienes somos</h3>
				<p>Conoscanos sepa quines somos documentese...</p>
				<p><a href="#" class="btn btn-primary " role="button">Button</a> </p>
			</div>
		</div>
	</div>
	<div class="col-sm-5 col-md-3 ">
		<div class="thumbnail  ">
			<a href="#"><img class="imt img-responsive" src="http://www.centroantaris.org/wp-content/uploads/2014/09/quienes-somos2.jpg" alt="..."></a>
			<div class="caption tmt">
				<h3>Quienes somos</h3>
				<p>Conoscanos sepa quines somos documentese...</p>
				<p><a href="#" class="btn btn-primary " role="button">Button</a> </p>
			</div>
		</div>
	</div>
	<div class="col-sm-5 col-md-3 ">
		<div class="thumbnail  ">
			<a href="#">
			<img class="imt img tmt-responsive" src="http://www.centroantaris.org/wp-content/uploads/2014/09/quienes-somos2.jpg" alt="..."></a>
			<div class="caption">
				<h3>Quienes somos</h3>
				<br>
				<p><a href="#" class="btn btn-primary" role="button">Button <span class=" icon-info"></span></a> </p>
			</div>
		</div>
	</div>
</div>